// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4zy7Q0nqvSLN8sT2tojLnDVSSLW3LXTg',
    appId: '1:69656956778:web:780574ea8c36fde63f5f13',
    messagingSenderId: '69656956778',
    projectId: 'pushnotification-7f888',
    authDomain: 'pushnotification-7f888.firebaseapp.com',
    databaseURL: 'https://pushnotification-7f888.firebaseio.com',
    storageBucket: 'pushnotification-7f888.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFuUNjowt52C1D8wezQXgXvahPep_DjE',
    appId: '1:69656956778:android:4c301e7c18d14c073f5f13',
    messagingSenderId: '69656956778',
    projectId: 'pushnotification-7f888',
    databaseURL: 'https://pushnotification-7f888.firebaseio.com',
    storageBucket: 'pushnotification-7f888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg4be4IMxwcm0D0QSH6JAR9oKhe5BgqpY',
    appId: '1:69656956778:ios:62074e121c1e24d03f5f13',
    messagingSenderId: '69656956778',
    projectId: 'pushnotification-7f888',
    databaseURL: 'https://pushnotification-7f888.firebaseio.com',
    storageBucket: 'pushnotification-7f888.appspot.com',
    iosClientId: '69656956778-mt488283rddijl4s92dioml62f39egsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg4be4IMxwcm0D0QSH6JAR9oKhe5BgqpY',
    appId: '1:69656956778:ios:62074e121c1e24d03f5f13',
    messagingSenderId: '69656956778',
    projectId: 'pushnotification-7f888',
    databaseURL: 'https://pushnotification-7f888.firebaseio.com',
    storageBucket: 'pushnotification-7f888.appspot.com',
    iosClientId: '69656956778-mt488283rddijl4s92dioml62f39egsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4zy7Q0nqvSLN8sT2tojLnDVSSLW3LXTg',
    appId: '1:69656956778:web:c40a555955dcad9b3f5f13',
    messagingSenderId: '69656956778',
    projectId: 'pushnotification-7f888',
    authDomain: 'pushnotification-7f888.firebaseapp.com',
    databaseURL: 'https://pushnotification-7f888.firebaseio.com',
    storageBucket: 'pushnotification-7f888.appspot.com',
  );
}
